module.exports = {
  parser: '@typescript-eslint/parser',
  extends: ['turbo', 'prettier', 'plugin:@typescript-eslint/recommended'],
  plugins: ['prettier', 'header', '@typescript-eslint/eslint-plugin'],
  env: { node: true, jest: true },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    'prettier/prettier': 'error',
    'header/header': [
      'error',
      'block',
      [
        '*',
        ' * Copyright 2023 LINE Corporation',
        ' *',
        ' * LINE Corporation licenses this file to you under the Apache License,',
        ' * version 2.0 (the "License"); you may not use this file except in compliance',
        ' * with the License. You may obtain a copy of the License at:',
        ' *',
        ' *   https://www.apache.org/licenses/LICENSE-2.0',
        ' *',
        ' * Unless required by applicable law or agreed to in writing, software',
        ' * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT',
        ' * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the',
        ' * License for the specific language governing permissions and limitations',
        ' * under the License.',
        ' ',
      ],
      1,
    ],
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      },
    ],
    'no-unused-vars': 'off',
  },
  overrides: [
    {
      files: ['!src/**/*.{ts,tsx}'],
      rules: {
        'header/header': 'off',
      },
    },
  ],
};
