version: '3'

services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_MAX_DAYS=90
      - API_BASE_URL=http://api:4000
      - SESSION_PASSWORD=sessionpasswordsessionpasswordsessionpassword
    depends_on:
      - api
    networks:
      - app_network

  api:
    hostname: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@mysql:3306/userfeedback
      - MYSQL_SECONDARY_URLS=["mysql://userfeedback:userfeedback@mysql:3306/userfeedback"]
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_SENDER=abc@feedback.user
      - SMTP_BASE_URL=http://localhost:3000
      - APP_PORT=4000
      - APP_ADDRESS=api
      - AUTO_MIGRATION=true
      - MASTER_API_KEY=MASTER_API_KEY
      - NODE_OPTIONS="--max_old_space_size=3072"
    networks:
      - app_network

networks:
  app_network:
