version: "3"

services:
  web:
    hostname: web
    image: harbor.linecorp.com/abc-studio/user-feedback/web:ui
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_MAX_DAYS=90
      - SESSION_PASSWORD=sessionpasswordsessionpasswordsessionpassword
    depends_on:
      - api
    networks:
      - app_network

  api:
    hostname: api
    build:
      context: ..
      dockerfile: docker/api.dockerfile
      args:
        - TURBO_TOKEN=TURBO_TOKEN
        - TURBO_TEAM=TURBO_TEAM
    restart: always
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@mysql:3306/userfeedback
      - BASE_URL=http://api:3000
      - ACCESS_TOKEN_EXPIRED_TIME=10m
      - REFESH_TOKEN_EXPIRED_TIME=1h
      - APP_PORT=4000
      - APP_ADDRESS=api
      - AUTO_MIGRATION=true
      - NODE_OPTIONS="--max_old_space_size=3072"
    networks:
      - app_network

networks:
  app_network:
