services:
  web:
    container_name: ufb-web
    image: line/abc-user-feedback-web:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - api

  api:
    container_name: ufb-api
    image: line/abc-user-feedback-api:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@mysql:3306/userfeedback
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_SENDER=user@feedback.com
      - OPENSEARCH_USE=true
      - OPENSEARCH_NODE=http://opensearch-node:9200
      - OPENSEARCH_USERNAME=""
      - OPENSEARCH_PASSWORD=""
