services:
  web:
    hostname: web
    image: line/abc-user-feedback-web:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_MAX_DAYS=90
    depends_on:
      - api
    networks:
      - app_network

  api:
    hostname: api
    image: line/abc-user-feedback-api:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@mysql:3306/userfeedback
      - BASE_URL=http://api:3000
      - ACCESS_TOKEN_EXPIRED_TIME=10m
      - REFESH_TOKEN_EXPIRED_TIME=1h
      - APP_PORT=4000
      - APP_ADDRESS=api
      - AUTO_MIGRATION=true
      - NODE_OPTIONS="--max_old_space_size=3072"
    networks:
      - app_network

networks:
  app_network:
